categories_list = [
	{"id": 0, "name": "Мягкая мебель", "group": 2},
	{"id": 1, "name": "Кухни/корпусная мебель", "group": 2},
	{"id": 2, "name": "Стулья", "group": 2},
	{"id": 3, "name": "Умный дом/домашний кинотеатр", "group": 2},
	{"id": 4, "name": "Декоративные штукатурки", "group": 2},
	{"id": 5, "name": "Краски", "group": 2},
	{"id": 6, "name": "Обои", "group": 2},
	{"id": 7, "name": "Свет", "group": 2},
	{"id": 8, "name": "Сантехника/мебель для ванн", "group": 2},
	{"id": 9, "name": "Плитка/керамогранит", "group": 2},
	{"id": 10, "name": "Двери", "group": 2},
	{"id": 11, "name": "Стекло", "group": 2},
	{"id": 12, "name": "Камины", "group": 2},
	{"id": 13, "name": "Декор", "group": 2},
	{"id": 14, "name": "Окна", "group": 2},
	{"id": 15, "name": "Вентиляция", "group": 2},
	{"id": 16, "name": "Строительство и ремонт", "group": 2},
	{"id": 17, "name": "Ткани", "group": 2},
	{"id": 18, "name": "Услуги клининга", "group": 2},
	{"id": 19, "name": "Услуги перепланировки", "group": 2},
	{"id": 20, "name": "Дизайнер интерьера", "group": 0},
	{"id": 21, "name": "Архитектор", "group": 0},
	{"id": 22, "name": "Визуализатор", "group": 1},
	{"id": 23, "name": "Стилист интерьера", "group": 1},
	{"id": 24, "name": "Декоратор", "group": 1},
	{"id": 25, "name": "Ландшафтный дизайнер", "group": 1},
	{"id": 26, "name": "Проектировщик", "group": 1},
	{"id": 27, "name": "Чертежник", "group": 1},
	{"id": 28, "name": "Фотограф", "group": 1},
]

users_list = [
	{'id': 0, 'category': 15, 'name': 'AleksaFlex', 'address': 'Пролетарская, 14'},
	{'id': 1, 'category': 15, 'name': 'Divanger', 'address': 'Ленина, 205'},
	{'id': 2, 'category': 15, 'name': 'Dom Design', 'address': 'Спасская, 17'},
	{'id': 3, 'category': 15, 'name': 'Диваны Moon', 'address': 'Ленина, 205, Герцена, 88'},
	{'id': 4, 'category': 15, 'name': 'Mobel & Zeit', 'address': 'Ленина, 205'},
	{'id': 5, 'category': 15, 'name': 'Sofmann', 'address': 'Ленина, 205'},
	{'id': 6, 'category': 15, 'name': 'Vernisage', 'address': 'Комсомольская, 14'},
	{'id': 7, 'category': 15, 'name': 'Диваны eXpress', 'address': 'Ленина, 205'},
	{'id': 8, 'category': 15, 'name': 'Мебель братьев Баженовых', 'address': 'Герцена, 88'},
	{'id': 9, 'category': 15, 'name': 'Нико', 'address': 'Герцена, 42Б'},
	{'id': 10, 'category': 15, 'name': 'Формула дивана', 'address': 'Ленина, 205'},
	{'id': 11, 'category': 15, 'name': 'Шубин мебель', 'address': 'ИП Шубин Юрий'},
	{'id': 12, 'category': 16, 'name': 'А-студия Мебельная студия', 'address': 'Труда, 71'},
	{'id': 13, 'category': 16, 'name': 'Алькасар', 'address': 'Герцена, 9'},
	{'id': 14, 'category': 16, 'name': 'Вятские кустарные мастерские', 'address': 'Заводская, 47'},
	{'id': 15, 'category': 16, 'name': 'Знатная мебель (ИП Козлов)', 'address': 'Щорса, 64а'},
	{'id': 16, 'category': 16, 'name': 'Киров Мебель', 'address': 'Дзержинского, 68'},
	{'id': 17, 'category': 16, 'name': 'Кухонный двор', 'address': 'ул. Ленина 205'},
	{'id': 18, 'category': 16, 'name': 'Лофт43', 'address': 'Ленина, 2/1'},
	{'id': 19, 'category': 16, 'name': 'Мебелит', 'address': 'Ленина, 89'},
	{'id': 20, 'category': 16, 'name': 'Мебель VASHLOFT & EGOS', 'address': 'Больничный пр. 3а'},
	{'id': 21, 'category': 16, 'name': 'Мебельные технологии', 'address': 'Милицейская, 76а'},
	{'id': 22, 'category': 16, 'name': 'МЕЛЬЕ', 'address': 'Ленина, 87'},
	{'id': 23, 'category': 16, 'name': 'РИМИ', 'address': 'Володарского, 157'},
	{'id': 24, 'category': 16, 'name': 'Стильные кухни', 'address': 'Блюхера, 39Б'},
	{'id': 25, 'category': 16, 'name': 'Студия Кухни', 'address': 'Карла Маркса, 47'},
	{'id': 26, 'category': 16, 'name': 'Студия Предмет', 'address': 'ул. Солнечная 8В'},
	{'id': 27, 'category': 16, 'name': 'ИП Шубин Александр (корпусная мебель)'},
	{'id': 28, 'category': 16, 'name': 'Amira home', 'address': 'Октябрьский пр. 149'},
	{'id': 29, 'category': 16, 'name': 'Мебельная студия Anna', 'address': 'Спасская, 61'},
	{'id': 30, 'category': 16, 'name': 'Belroom', 'address': 'Ленина, 205'},
	{'id': 31, 'category': 16, 'name': 'Evita', 'address': 'Ленина, 205'},
	{'id': 32, 'category': 16, 'name': 'Garda Décor', 'address': 'Ленина, 205'},
	{'id': 33, 'category': 16, 'name': 'Giulia Novars', 'address': 'Октябрьский пр. 80'},
	{'id': 34, 'category': 16, 'name': 'Кухни Greta', 'address': 'Октябрьский пр. 149'},
	{'id': 35, 'category': 16, 'name': 'Hamiltoun', 'address': 'Попова, 71'},
	{'id': 36, 'category': 16, 'name': 'In Fashion', 'address': 'Ленина, 193'},
	{'id': 37, 'category': 16, 'name': 'Lithium', 'address': 'Казанская, 77Б'},
	{'id': 38, 'category': 16, 'name': 'Lorena', 'address': 'Пролетарская, 14'},
	{'id': 39, 'category': 16, 'name': 'Mazeev Gruppo', 'address': 'Садаковский, Московская, 40'},
	{'id': 40, 'category': 16, 'name': 'Mebeloff', 'address': 'Октябрьский проспект, 80'},
	{'id': 41, 'category': 16, 'name': 'Profi-Form', 'address': 'Орловская, 11'},
	{'id': 42, 'category': 16, 'name': 'Rits', 'address': 'Ленина, 116'},
	{'id': 43, 'category': 16, 'name': 'SETUS Production', 'address': 'Герцена, 28'},
	{'id': 44, 'category': 16, 'name': 'Spectrum', 'address': 'Советский тракт, 1'},
	{'id': 45, 'category': 16, 'name': 'STOLYAR', 'address': 'Калинина, 40'},
	{'id': 46, 'category': 16, 'name': 'Фабрика мебели Veroom', 'address': 'Лепсе, 12'},
	{'id': 49, 'category': 17, 'name': 'ДЭФО мебель', 'address': 'Профсоюзная, 1'},
	{'id': 50, 'category': 17, 'name': 'Вишневый сад', 'address': ''},
	{'id': 51, 'category': 17, 'name': 'ChiedoСover', 'address': 'Орловская, 4'},
	{'id': 52, 'category': 17, 'name': 'Dom Design', 'address': 'Спасская, 17'},
	{'id': 53, 'category': 17, 'name': 'Mazeev Gruppo', 'address': 'Садаковский, Московская, 40'},
]
